/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n8.0.1-14-gfe72a8781b-20251128"
#endif /* AVUTIL_FFVERSION_H */
